import{a as B,S as h,i as l}from"./assets/vendor-CVqJO7b2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function e(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(o){if(o.ep)return;o.ep=!0;const n=e(o);fetch(o.href,n)}})();const I="42306432-61ab7fb6a7e28dda5f126fb86";async function y(t,r=1,e=15){try{return(await B.get(`https://pixabay.com/api/?key=${I}&q=${t}&page=${r}&per_page=${e}`)).data}catch(a){throw console.error("Error fetching data:",a),a}}const b=document.getElementById("loader"),$=document.getElementById("gallery"),v=new h(".gallery a"),m=document.getElementById("loadMoreBtn");function g(t,r){if(r&&(b.style.display="none"),t.length===0){l.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}),c();return}t.forEach(e=>{const a=document.createElement("div");a.classList.add("card"),a.innerHTML=`
            <a href="${e.largeImageURL}" data-lightbox="gallery">
                <img src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <p>Likes: ${e.likes}</p>
            <p>Views: ${e.views}</p>
            <p>Comments: ${e.comments}</p>
            <p>Downloads: ${e.downloads}</p>
        `,$.appendChild(a)}),v.refresh()}function c(){m.style.display="none"}function O(){m.style.display="block"}function u(){l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}const P=document.getElementById("loader"),M=document.getElementById("gallery");new h(".gallery a");const S=document.getElementById("loadMoreBtn"),A=document.getElementById("searchForm"),p=document.getElementById("searchInput"),E="block",L="none";function i(t){P.style.display=t}let s=1,f=!1;A.addEventListener("submit",async function(t){t.preventDefault();const r=p.value.trim();if(r===""){l.error({title:"Error",message:"Please enter a search term"});return}i(E),M.innerHTML="",s=1,f=!1;try{const e=await y(r,s);g(e.hits,!0),e.hits.length===0?(c(),u()):(O(),s++,w())}catch(e){console.error("Error fetching data:",e),l.error({title:"Error",message:"An error occurred while fetching data. Please try again."})}finally{i(L)}});S.addEventListener("click",async function(){try{if(f){c(),u();return}const t=p.value.trim();i(E);const r=await y(t,s);r.hits.length===0?(f=!0,c(),u()):(g(r.hits,!1),s++,w())}catch(t){console.error("Error fetching data:",t),l.error({title:"Error",message:"An error occurred while fetching more data. Please try again."})}finally{i(L)}});function w(){var r,e;const t=(e=(r=document.querySelector(".card"))==null?void 0:r.getBoundingClientRect())==null?void 0:e.height;t&&window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
