import{a as w,S as L,i as c}from"./assets/vendor-CVqJO7b2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=e(t);fetch(t.href,n)}})();const b="42306432-61ab7fb6a7e28dda5f126fb86";async function u(r,o=1,e=15){try{return(await w.get(`https://pixabay.com/api/?key=${b}&q=${r}&page=${o}&per_page=${e}`)).data}catch(s){throw console.error("Error fetching data:",s),s}}const B=document.getElementById("loader"),I=document.getElementById("gallery"),$=new L(".gallery a"),f=document.getElementById("loadMoreBtn");function h(r,o){if(B.style.display="none",r.length===0){c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}),i();return}o&&y(),r.forEach(e=>{const s=document.createElement("div");s.classList.add("card"),s.innerHTML=`
            <a href="${e.largeImageURL}" data-lightbox="gallery">
                <img src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <p>Likes: ${e.likes}</p>
            <p>Views: ${e.views}</p>
            <p>Comments: ${e.comments}</p>
            <p>Downloads: ${e.downloads}</p>
        `,I.appendChild(s)}),$.refresh()}function i(){f.style.display="none"}function y(){f.style.display="block"}function m(){c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}const v=document.getElementById("searchForm"),g=document.getElementById("searchInput"),d=document.getElementById("loader"),M=document.getElementById("gallery"),p=document.getElementById("loadMoreBtn");let a=1;v.addEventListener("submit",async function(r){r.preventDefault();const o=g.value.trim();if(o===""){c.error({title:"Error",message:"Please enter a search term"});return}d.style.display="block",M.innerHTML="";try{const e=await u(o,a);h(e.hits,a===1),e.hits.length===0?(i(),m()):(y(),a++,E())}catch(e){d.style.display="none",console.error("Error fetching data:",e),c.error({title:"Error",message:"An error occurred while fetching data. Please try again."})}});p.addEventListener("click",async()=>{try{const r=g.value.trim(),o=await u(r,a);h(o.hits,!1),o.hits.length===0?(i(),m()):(a++,E())}catch(r){console.error("Error fetching data:",r),c.error({title:"Error",message:"An error occurred while fetching more data. Please try again."})}});function E(){const r=document.querySelector(".card").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}p.addEventListener;
//# sourceMappingURL=commonHelpers.js.map
